services:
  backend:
    image: REDACTED:5050/team-4/backend:latest
    restart: unless-stopped
    # ports:
    #   - ${BACKEND_PORT}:80
    depends_on:
      - postgres
      - minio
    env_file: .env
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crmbackend.rule=Host(`prod-team-4-1u3kkm05.REDACTED`) && PathPrefix(`/api`)"
      - "traefik.http.routers.crmbackend.entrypoints=web,websecure"
      - "traefik.http.services.crmbackend.loadbalancer.server.port=80"
      - "traefik.http.routers.crmbackend.tls.certresolver=leresolver"
      - "traefik.http.routers.crmbackend.middlewares=testheader"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MINIO_HOST: minio
      MINIO_PORT: 9000

  postgres:
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    env_file: .env

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    networks:
      - default
    entrypoint: /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5 &&
      mc alias set local http://localhost:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb local/${MINIO_BUCKET} || true;
      wait
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
    # ports:
    #   - ${MINIO_PORT}:9000
    #   - ${MINIO_CONSOLE_PORT}:9001
    labels:
      - "traefik.enable=false"
    volumes:
      - minio_data:/data
    env_file: .env

  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`prod-team-4-1u3kkm05.REDACTED`) && PathPrefix(`/pgadmin`)"
      - "traefik.http.routers.pgadmin.entrypoints=web,websecure"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.tls.certresolver=leresolver"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=zethange@yandex.ru"
      - "PGADMIN_DEFAULT_PASSWORD=SuperSecretPassword"
      - "SCRIPT_NAME=/pgadmin"

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - web
    command:
      - '--base-url="/portainer"'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`prod-team-4-1u3kkm05.REDACTED`) && PathPrefix(`/portainer`)"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
      - "traefik.http.routers.portainer.tls.certresolver=leresolver"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  minio_data:
  portainer_data:

networks:
  web:
    external: true
  default:
